name: Build and Push image
description: 'Builds an image, pushes to artifact registry, and caches to gha as well as the `cache` tag'
inputs:
  secrets:
    description: docker build secrets, newline separated string key=value
    required: false
    default: |
      "gitPat=${{ secrets.GIT_RUNNER_TOKEN }}"
  tag-name:
    description: tag name, i.e. 'event-stream'
    required: false
    default: ${{ github.event.repository.name }}
  tags:
    description: git tags to push
    required: false
    default: |
      ${{ secrets.GAR_IMAGES_REPO }}/${{ inputs.tag-name }}:${{ github.event.release.tag_name }}
      ${{ secrets.GAR_IMAGES_REPO }}/${{ inputs.tag-name }}:latest
runs:
  using: composite
  steps:
    - uses: crazy-max/ghaction-dump-context@v1
    - uses: actions/checkout@v2
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GAR_WRITE_SERVICE_ACCOUNT_KEY }}
    - uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID_PROD }}
    - shell: bash
      run: |
        gcloud auth configure-docker ${{ secrets.GAR_REGION }}-docker.pkg.dev
    - uses: docker/setup-buildx-action@v1
    - id: build-image
      uses: docker/build-push-action@v2
      with:
        secrets: ${{ inputs.secrets }}
        tags: ${{ inputs.tags }}
        push: true
        cache-from: type=gha,mode=max
        cache-to: type=gha,mode=max
        no-cache: ${{ contains(github.event.head_commit.message, 'no-cache') }} # in case we need to change the secret value
    - name: Cache to gar cache tag
      # buildkit doesn't support multiple cache-to destinations yet. But we want to cache in gha as well as gar
      # so that others can use the cache from the repository. So adding this step here to build from gha cache
      # and cache to gar cache tag
      uses: docker/build-push-action@v2
      with:
        secrets: ${{ inputs.secrets }}
        cache-from: type=gha,mode=max
        cache-to: type=registry,ref=${{ secrets.GAR_IMAGES_REPO }}/${{ inputs.tag-name }}:cache,mode=max