name: Semantic Release
on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main
#    paths:
#      - action.yaml
  push:
    branches:
      - main
jobs:
  semantic-release:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # this makes the semantic-release git plugin push as the runner, which allows us to bypass branch protection
          token: ${{ secrets.GIT_RUNNER_TOKEN }}
      - name: Dry run to get next version
        id: semantic-release-dry-run
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/exec
            conventional-changelog-conventionalcommits
            @semantic-release/changelog
            @semantic-release/git
        env:
          # github.token can't trigger workflows, we want the created release to trigger other workflows, so use the runner token
          GITHUB_TOKEN: ${{ secrets.GIT_RUNNER_TOKEN }}
      - uses: bitflight-devops/github-action-readme-generator@v1.0.12a
        with:
          action: ${{ github.workspace }}/action.yaml
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pretty: false
          versioning_enabled: true
          version_override: v${{ steps.semantic-release-dry-run.outputs.new_release_major_version }}
      - name: Reset major version tag
        run: |
          git tag -d v${{ steps.semantic-release-dry-run.outputs.new_release_major_version }} || true
          git push -d origin v${{ steps.semantic-release-dry-run.outputs.new_release_major_version }} || true
          git tag v${{ steps.semantic-release-dry-run.outputs.new_release_major_version }}
      - id: semantic-release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
            conventional-changelog-conventionalcommits
            @semantic-release/changelog
            @semantic-release/git
        env:
          # github.token can't trigger workflows, we want the created release to trigger other workflows, so use the runner token
          GITHUB_TOKEN: ${{ secrets.GIT_RUNNER_TOKEN }}